$mainMod = SUPER # Sets "Windows" key as main modifier

# Custom window rules

exec-once = [workspace 1 silent] flatpak run one.ablaze.floorp
exec-once = [workspace 2 silent] flatpak run dev.vencord.Vesktop  
exec-once = [workspace 3 silent] kitty --class startupTerminal -e tmux

windowrule = match:class ^(one.ablaze.floorp)$, workspace 1 silent
windowrule = match:class ^(vesktop)$, workspace 2 silent  
windowrule = match:class ^(startupTerminal)$, workspace 3 silent

# custom binds

bind = $mainMod, l, movewindow, r
bind = $mainMod, h, movewindow, l
bind = $mainMod, j, movewindow, d
bind = $mainMod, k, movewindow, u


# bind = $mainMod, S, exec, /home/dreamer/.config/scripts/screenshot.sh
bind = $mainMod, V, exec, cliphist list | fuzzel --dmenu | cliphist decode | wl-copy
bind = CTRL, PRINT, exec, ~/.config/waybar/scripts/screenshot_region_copy.sh
bind = ALT, PRINT, exec, ~/.config/waybar/scripts/colorpicker.sh
bind = $mainMod, F11, exec, ~/.config/waybar/scripts/toggle-waybar.sh

# Application Binds

bind = , grave, exec, flatpak run one.ablaze.floorp
bind = , XF86Mail, exec, flatpak run dev.vencord.Vesktop
