general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 4
}

input-field {
    size = 300, 60
    outline_thickness = 2
    outer_color = rgb(ffffff)
    inner_color = rgb(000000)
    font_color = rgb(ffffff)
    fade_on_empty = false
    placeholder_text = Password...
}
